# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of the film Director', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of the movie', max_length=255)),
                ('imdb_score', models.FloatField(default=0, help_text=b'Ratings')),
                ('genre', models.TextField(help_text=b'Drama, History, Romance (Comma separated values)')),
                ('popularity99', models.FloatField(default=0.0, help_text=b'How popular the movie is? (in %)')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_director', to='movie.Director')),
            ],
        ),
    ]
