# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='director_name',
        ),
    ]
